App:
  lastProcessed: 0
  appName: [APPNAME TO IDENTIFY EVENTS IN INSIGHTS]
  accountCommand: ["SELECT accountName as account FROM vwAccountUsers WHERE username = "]

Insights:
  hostname: insights-collector.newrelic.com
  path: "/v1/accounts/[NEW RELIC ACCOUNT ID]/events"
  insertKey: [NEW RELIC INSIGHTS INSERT KEY]
  appId: [NEW RELIC APM APP ID]

Database:
  server: [DATABASE IP OR ADDRESS]
  database: ReportServer
  user: [DATABASE USER NAME]
  password: [DATABASE USER PASSWORD]

DatabaseAccounts:
  server: [DATABASE IP OR ADDRESS]
  database: [DATABASE NAME]
  user: [DATABASE USER NAME]
  password: [DATABASE USER PASSWORD]
